services:
  postgres:
    image: postgres:17.1
    restart: always
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - '6500:5432'

  redis:
    image: redis:7.4.1
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    env_file:
      - ./.env
    volumes:
      - redis-data:/data
    networks:
      - backend
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onion-scraper
    env_file:
      - ./.env
    networks:
      - backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
networks:
  backend: